# Generated by Django 5.2.6 on 2025-09-20 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_files_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="delete_after",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name="folder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
