# Generated by Django 5.2.6 on 2025-09-21 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_folder_delete_after_alter_folder_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="download_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="folder",
            name="downloaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="folder",
            name="delete_after",
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
